"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getDb } from "@/lib/db";
import { getTemplate, findPlaceholders } from "@/lib/outreachTemplates";

function fail(path: string, message: string): never {
  redirect(`${path}${path.includes("?") ? "&" : "?"}error=${encodeURIComponent(message)}`);
}

function requireName(formData: FormData, back: string): string {
  const who = String(formData.get("entered_by") ?? "").trim().slice(0, 60);
  if (!who) fail(back, "Please enter your name — every action is recorded with who did it and when.");
  return who;
}

function revalidateOutreach(leadId: number | null, draftId?: number) {
  for (const p of ["/", "/outreach", "/leads"]) revalidatePath(p);
  if (leadId) revalidatePath(`/leads/${leadId}`);
  if (draftId) revalidatePath(`/outreach/${draftId}`);
}

interface LeadForDraft {
  id: number;
  status: string;
  company_id: number | null;
  company_name: string | null;
  company_type: string | null;
  description: string | null;
  contact_name: string | null;
  market_country: string | null;
}

function leadForDraft(leadId: number): LeadForDraft | undefined {
  return getDb()
    .prepare(
      `SELECT l.id, l.status, l.company_id, c.name company_name, c.company_type, c.description,
              ct.full_name contact_name, m.country market_country
       FROM leads l
       LEFT JOIN companies c ON c.id = l.company_id
       LEFT JOIN contacts ct ON ct.id = l.contact_id
       LEFT JOIN markets m ON m.id = l.market_id
       WHERE l.id = ?`
    )
    .get(leadId) as LeadForDraft | undefined;
}

/** Absolute rule: no drafts for (or actions on) a Do-not-contact lead. */
function blockDoNotContact(status: string | null | undefined, back: string) {
  if (status === "Do not contact") {
    fail(back, "This lead is marked Do not contact. The system will not create, approve or send outreach for it under any circumstances.");
  }
}

export async function generateDraft(formData: FormData) {
  const leadId = Number(formData.get("lead_id"));
  const back = `/leads/${leadId}`;
  const db = getDb();
  const lead = leadForDraft(leadId);
  if (!lead) redirect("/leads");
  blockDoNotContact(lead.status, back);
  const who = requireName(formData, back);
  const template = getTemplate(String(formData.get("template_key") ?? ""));
  if (!template) fail(back, "Pick a template first.");
  if (!lead.company_name) fail(back, "This lead has no company — a draft needs a real recipient organisation.");

  const ctx = {
    contact_name: lead.contact_name,
    company_name: lead.company_name,
    company_type: lead.company_type,
    market_country: lead.market_country,
    description: lead.description,
  };
  const now = new Date().toISOString();
  const info = db
    .prepare(
      `INSERT INTO outreach_drafts (lead_id, channel, subject, body, status, template_key, created_by, created_at, updated_at)
       VALUES (?, ?, ?, ?, 'draft', ?, ?, ?, ?)`
    )
    .run(leadId, template.channel, template.subject ? template.subject(ctx) : null, template.body(ctx), template.key, who, now, now);
  const draftId = Number(info.lastInsertRowid);
  db.prepare(`INSERT INTO activities (lead_id, activity_type, description, created_at) VALUES (?, 'note', ?, ?)`).run(
    leadId,
    `Outreach draft #${draftId} (${template.label}) generated by ${who} — requires human review before any use`,
    now
  );
  revalidateOutreach(leadId, draftId);
  redirect(`/outreach/${draftId}?saved=${encodeURIComponent("Draft created. Review it, resolve every [PLACEHOLDER], then approve.")}`);
}

export async function updateDraft(formData: FormData) {
  const draftId = Number(formData.get("draft_id"));
  const back = `/outreach/${draftId}`;
  const db = getDb();
  const draft = db.prepare(`SELECT * FROM outreach_drafts WHERE id = ?`).get(draftId) as
    | { id: number; lead_id: number | null; status: string; channel: string }
    | undefined;
  if (!draft) redirect("/outreach");
  const who = requireName(formData, back);
  if (draft.status !== "draft") fail(back, `Only drafts in review can be edited (this one is "${draft.status}"). Use "Back to draft" first.`);
  const subject = String(formData.get("subject") ?? "").trim().slice(0, 300) || null;
  const body = String(formData.get("body") ?? "").trim().slice(0, 8000);
  if (!body) fail(back, "The draft body cannot be empty.");
  if (draft.channel === "email" && !subject) fail(back, "An email draft needs a subject line.");
  const now = new Date().toISOString();
  db.prepare(`UPDATE outreach_drafts SET subject = ?, body = ?, updated_at = ? WHERE id = ?`).run(subject, body, now, draftId);
  db.prepare(`INSERT INTO activities (lead_id, activity_type, description, created_at) VALUES (?, 'note', ?, ?)`).run(
    draft.lead_id, `Draft #${draftId} edited by ${who}`, now
  );
  revalidateOutreach(draft.lead_id, draftId);
  redirect(`${back}?saved=${encodeURIComponent("Draft saved.")}`);
}

export async function approveDraft(formData: FormData) {
  const draftId = Number(formData.get("draft_id"));
  const back = `/outreach/${draftId}`;
  const db = getDb();
  const draft = db
    .prepare(
      `SELECT d.*, l.status lead_status FROM outreach_drafts d LEFT JOIN leads l ON l.id = d.lead_id WHERE d.id = ?`
    )
    .get(draftId) as { id: number; lead_id: number | null; status: string; body: string | null; subject: string | null; lead_status: string | null } | undefined;
  if (!draft) redirect("/outreach");
  blockDoNotContact(draft.lead_status, back);
  const who = requireName(formData, back);
  if (draft.status !== "draft") fail(back, `Only a draft in review can be approved (this one is "${draft.status}").`);
  const placeholders = findPlaceholders(`${draft.subject ?? ""}\n${draft.body ?? ""}`);
  if (placeholders.length > 0) {
    fail(back, `Resolve these placeholders before approving: ${placeholders.join(" ")}`);
  }
  const now = new Date().toISOString();
  db.prepare(`UPDATE outreach_drafts SET status = 'approved', approved_by = ?, approved_at = ?, updated_at = ? WHERE id = ?`).run(who, now, now, draftId);
  db.prepare(`INSERT INTO activities (lead_id, activity_type, description, created_at) VALUES (?, 'note', ?, ?)`).run(
    draft.lead_id, `Draft #${draftId} approved by ${who} — to be sent manually, never automatically`, now
  );
  revalidateOutreach(draft.lead_id, draftId);
  redirect(`${back}?saved=${encodeURIComponent("Approved. Copy the text and send it yourself, then mark it sent.")}`);
}

export async function revertDraft(formData: FormData) {
  const draftId = Number(formData.get("draft_id"));
  const back = `/outreach/${draftId}`;
  const db = getDb();
  const draft = db.prepare(`SELECT id, lead_id, status FROM outreach_drafts WHERE id = ?`).get(draftId) as
    | { id: number; lead_id: number | null; status: string }
    | undefined;
  if (!draft) redirect("/outreach");
  const who = requireName(formData, back);
  if (draft.status !== "approved") fail(back, "Only an approved draft can go back to review.");
  const now = new Date().toISOString();
  db.prepare(`UPDATE outreach_drafts SET status = 'draft', approved_by = NULL, approved_at = NULL, updated_at = ? WHERE id = ?`).run(now, draftId);
  db.prepare(`INSERT INTO activities (lead_id, activity_type, description, created_at) VALUES (?, 'note', ?, ?)`).run(
    draft.lead_id, `Draft #${draftId} moved back to review by ${who}`, now
  );
  revalidateOutreach(draft.lead_id, draftId);
  redirect(`${back}?saved=${encodeURIComponent("Moved back to draft for editing.")}`);
}

export async function markDraftSent(formData: FormData) {
  const draftId = Number(formData.get("draft_id"));
  const back = `/outreach/${draftId}`;
  const db = getDb();
  const draft = db
    .prepare(
      `SELECT d.*, l.status lead_status FROM outreach_drafts d LEFT JOIN leads l ON l.id = d.lead_id WHERE d.id = ?`
    )
    .get(draftId) as { id: number; lead_id: number | null; status: string; channel: string; lead_status: string | null } | undefined;
  if (!draft) redirect("/outreach");
  blockDoNotContact(draft.lead_status, back);
  const who = requireName(formData, back);
  if (draft.status !== "approved") fail(back, "Only an approved draft can be marked as sent. Approve it first.");
  const makeReminder = formData.get("create_reminder") === "on";
  const advanceStatus = formData.get("advance_status") === "on";
  const now = new Date();
  const nowIso = now.toISOString();

  const tx = db.transaction(() => {
    db.prepare(`UPDATE outreach_drafts SET status = 'sent_manually', sent_by = ?, sent_at = ?, updated_at = ? WHERE id = ?`).run(who, nowIso, nowIso, draftId);
    db.prepare(`INSERT INTO activities (lead_id, activity_type, description, created_at) VALUES (?, ?, ?, ?)`).run(
      draft.lead_id,
      draft.channel === "email" ? "email_sent_manually" : "linkedin_manual",
      `Draft #${draftId} (${draft.channel}) sent MANUALLY by ${who} from their own account`,
      nowIso
    );
    if (advanceStatus && draft.lead_id && ["New", "Imported", "Needs research", "Reviewed", "Cold", "Approved for outreach"].includes(draft.lead_status ?? "")) {
      db.prepare(`UPDATE leads SET status = 'Contacted', updated_at = ? WHERE id = ?`).run(nowIso, draft.lead_id);
      db.prepare(`INSERT INTO activities (lead_id, activity_type, description, created_at) VALUES (?, 'status_change', ?, ?)`).run(
        draft.lead_id, `Status changed from "${draft.lead_status}" to "Contacted" by ${who} (outreach sent)`, nowIso
      );
    }
    if (makeReminder && draft.lead_id) {
      const due = new Date(now.getTime() + 7 * 24 * 3600 * 1000).toISOString().slice(0, 10);
      db.prepare(`INSERT INTO activities (lead_id, activity_type, description, due_at, created_at) VALUES (?, 'reminder', ?, ?, ?)`).run(
        draft.lead_id, `Follow up on ${draft.channel} outreach (draft #${draftId}) if no reply`, due, nowIso
      );
    }
  });
  tx();
  revalidateOutreach(draft.lead_id, draftId);
  redirect(`${back}?saved=${encodeURIComponent("Recorded as sent manually." + (makeReminder ? " Follow-up reminder set for 7 days from now." : ""))}`);
}

export async function discardDraft(formData: FormData) {
  const draftId = Number(formData.get("draft_id"));
  const back = `/outreach/${draftId}`;
  const db = getDb();
  const draft = db.prepare(`SELECT id, lead_id, status FROM outreach_drafts WHERE id = ?`).get(draftId) as
    | { id: number; lead_id: number | null; status: string }
    | undefined;
  if (!draft) redirect("/outreach");
  const who = requireName(formData, back);
  if (draft.status === "sent_manually") fail(back, "A sent draft is a historical record and cannot be discarded.");
  const now = new Date().toISOString();
  db.prepare(`UPDATE outreach_drafts SET status = 'discarded', updated_at = ? WHERE id = ?`).run(now, draftId);
  db.prepare(`INSERT INTO activities (lead_id, activity_type, description, created_at) VALUES (?, 'note', ?, ?)`).run(
    draft.lead_id, `Draft #${draftId} discarded by ${who}`, now
  );
  revalidateOutreach(draft.lead_id, draftId);
  redirect(`/outreach?saved=${encodeURIComponent(`Draft #${draftId} discarded.`)}`);
}

// --- reminders -------------------------------------------------------------
export async function createReminder(formData: FormData) {
  const leadId = Number(formData.get("lead_id"));
  const back = `/leads/${leadId}`;
  const db = getDb();
  const lead = db.prepare(`SELECT id, status FROM leads WHERE id = ?`).get(leadId) as { id: number; status: string } | undefined;
  if (!lead) redirect("/leads");
  const who = requireName(formData, back);
  const description = String(formData.get("description") ?? "").trim().slice(0, 300);
  if (!description) fail(back, "Describe what the reminder is for.");
  const due = String(formData.get("due_at") ?? "").trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(due)) fail(back, "Pick a due date.");
  if (due < new Date().toISOString().slice(0, 10)) fail(back, "The due date is in the past.");
  const now = new Date().toISOString();
  db.prepare(`INSERT INTO activities (lead_id, activity_type, description, due_at, created_at) VALUES (?, 'reminder', ?, ?, ?)`).run(
    leadId, `${description} (set by ${who})`, due, now
  );
  revalidateOutreach(leadId);
  redirect(`${back}?saved=${encodeURIComponent(`Reminder set for ${due}.`)}`);
}

export async function completeReminder(formData: FormData) {
  const activityId = Number(formData.get("activity_id"));
  const backTo = String(formData.get("back") ?? "/outreach");
  const db = getDb();
  const activity = db.prepare(`SELECT id, lead_id, due_at, completed_at FROM activities WHERE id = ?`).get(activityId) as
    | { id: number; lead_id: number | null; due_at: string | null; completed_at: string | null }
    | undefined;
  if (!activity || !activity.due_at) fail(backTo, "Reminder not found.");
  const who = requireName(formData, backTo);
  if (activity.completed_at) fail(backTo, "That reminder is already done.");
  const now = new Date().toISOString();
  db.prepare(`UPDATE activities SET completed_at = ? WHERE id = ?`).run(now, activityId);
  db.prepare(`INSERT INTO activities (lead_id, activity_type, description, created_at) VALUES (?, 'note', ?, ?)`).run(
    activity.lead_id, `Reminder #${activityId} marked done by ${who}`, now
  );
  revalidateOutreach(activity.lead_id);
  redirect(`${backTo}?saved=${encodeURIComponent("Reminder marked done.")}`);
}
